### PR TITLE
Remove the "Gapless Playback" setting

### PR DESCRIPTION
**Pull request by hades**
This setting did not affect anything (see Player.kt:66).

Fortunately, with ExoPlayer the playback is gapless by default as long as media items are added to the player in advance. Testing on an actual device shows that the current implementation plays media without any gaps.

#### What is it?
- [ ] Bugfix
- [ ] Feature
- [x] Codebase improvement

#### Description of the changes in your PR

- Removed unimplemented setting
- Removed unused code

#### Before/After Screenshots/Screen Record

- Before: 
image

- After: 
image

#### Acknowledgement
- [x] I read the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Aga-C** [comment]
Please remove `GAPLESS_PLAYBACK` from Constants.kt and `gapless_playback` from all strings.xml files.

**Comment by hades** [comment]
> Please remove `GAPLESS_PLAYBACK` from Constants.kt and `gapless_playback` from all strings.xml files.

Done, thanks for the review!

**Comment by hades** [comment]
Ping?

**Comment by Aga-C** [comment]
@hades Please wait a bit more for the final review by Naveen. There's a lot of work to do related to releasing the whole Fossify suite, but we remember about your PR and will come back to it.

**Comment by hades** [comment]
Awesome, thanks for letting me know!

**Comment by naveensingh** [comment]
@hades Playback is always gapless (kind of) so it doesn't need a switch but I wanted to reuse that preference to enable skip silence as mentioned in Player.kt:

https://github.com/FossifyOrg/Music-Player/blob/60688c8f378b6fc75875181fb4142f31c1132f77/app/src/main/kotlin/org/fossify/musicplayer/playback/player/Player.kt#L67-L70

And the mentioned https://github.com/androidx/media/issues/712 is now resolved but I might reevaluate and remove this slightly misleading preference.

We might need this preference back if and when we decide to add "true gapless playback".

**Comment by hades** [comment]
@naveensingh I would argue for deleting the code anyway. You can always get it back from Git history, and until such time that you want it back, you will get less confused users and cleaner code.

Also, I'm not sure what you mean by "skip silence" or "true gapless playback". To me it sounds like a feature for podcast players or audiobook players that removes silence between sentences to make the episodes shorter. For a music player, I would personally never want such a feature, and I've never seen anyone request it (I used to work on Amarok many many years ago). Furthermore, even if you build such a feature, I would argue that reusing this preference would be incorrect: there may be users who have already enabled it expecting a different behaviour.

If you would like to move this discussion elsewhere, let me know. I can open a discussion post, or join your chat room, whatever you prefer.

**Comment by naveensingh** [comment]
@hades 

> Also, I'm not sure what you mean by "skip silence" or "true gapless playback".

"Skip silence", as you would expect, skips any silence in the audio being played. I agree, it wasn't the best idea to disguise it as "Gapless playback." 

By "true gapless playback", I meant absolutely zero gaps. Currently, the transition from one track to another is as seamless as possible but it's not truly gapless. You will notice a small gap with some tracks. The easiest way to reproduce it is using a sine wave split into multiple parts. That being said, I think ExoPlayer's seamless transition is sufficient for most gapless albums so we likely won't complicate things using concatenated media sources.

> I would personally never want such a feature, and I've never seen anyone request it

I don't know about skipping silence but SMT users did request gapless playback: https://github.com/SimpleMobileTools/Simple-Music-Player/issues/326. 

> If you would like to move this discussion elsewhere, let me know

No need for any more discussions. See https://github.com/SimpleMobileTools/Simple-Music-Player/pull/593, https://github.com/SimpleMobileTools/Simple-Music-Player/pull/595#issuecomment-1706114564 for more info.

**Comment by hades** [comment]
> You will notice a small gap with some tracks.

I would argue that this should be investigated separately as a bug. If you have examples of such tracks, I'd be happy to debug the root cause. Gapless playback is advertised as a feature of Exoplayer[1], so we can reasonably expect that to work without workarounds :)

Is it possible that the tracks you've experienced this with are MP3 tracks? MP3 adds extra samples of silence when decoded, and therefore requires additional metadata to correctly trim them (unlike, e.g. Ogg Vorbis, which includes such metadata as part of the format).

[1] https://medium.com/google-exoplayer/exoplayer-2-x-new-audio-features-cfb26c2883a

**Pull request merged**
